language: python
python:
  # - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.5-dev" # 3.5 development branch
  # - "pypy"
# command to install dependencies
# cache:
#   directories:
#     - $HOME/.cache/pip
install: 
- python setup.py develop
# command to run tests
script: 
- nosetests
# addons:
#   apt:
#     # sources:
#     # - ubuntu-toolchain-r-test
#     packages:
#     - python-matplotlib
#     - python-numpy
#     - python-yaml
#     - wkhtmltopdf
#     - pypy-dev
#     - python-cffi  # for pypy/numpy
#     # - python-cjson disallowed by Travis!
#     # - python-pil not found on Travis
#     - graphviz # TODO: add check for existence
